<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'" />

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Title>Lombiq UI Kit - Widgets for Orchard Core</Title>
    <Copyright>Copyright © 2024, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq UI Kit - Widgets for Orchard Core: This module contains widgets based on shapes from Lombiq UI Kit. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;UI;UIKit;Widgets;front-end</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-UIKit</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-UIKit/blob/dev/Lombiq.UIKit.Widgets/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Contents" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Flows" Version="2.1.0" />
    <PackageReference Include="OrchardCore.Media" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="..\Lombiq.UIKit\Lombiq.UIKit.csproj" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true'" />

</Project>
