<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.25.osoe-925" />

  <PropertyGroup>
    <Title>Lombiq UI Kit - Widgets for Orchard Core</Title>
    <CopyrightYear>2024</CopyrightYear>
    <DescriptionBody>This module contains widgets based on shapes from Lombiq UI Kit.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;UI;UIKit;Widgets;front-end</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-UIKit</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-UIKit/blob/dev/Lombiq.UIKit.Widgets/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Flows" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Media" Version="$(OrchardCoreVersion)" />
  </ItemGroup>

  <ItemGroup>
      <ProjectReference Include="..\Lombiq.UIKit\Lombiq.UIKit.csproj" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.25.osoe-925" />
</Project>
