namespace Lombiq.UIKit.Widgets.Constants;
public static class DefaultValues
{
    public const bool Accessibility = true;
    public const bool AdaptiveHeight = false;
    public const bool Autoplay = false;
    public const int AutoplaySpeed = 1000;
    public const bool Arrows = true;
    public const string AsNavFor = "";
    public const string AppendArrows = "$(element)";
    public const string AppendDots = "$(element)";
    public const string PrevArrow = "<button type=\"button\" class=\"slick-prev\">Previous</button>";
    public const string NextArrow = "<button type=\"button\" class=\"slick-next\">Next</button>";
    public const bool CenterMode = false;
    public const string CenterPadding = "50px";
    public const string CssEase = "ease";
    public const bool Dots = true;
    public const string DotsClass = "slick-dots";
    public const bool Draggable = true;
    public const bool Fade = false;
    public const bool FocusOnSelect = false;
    public const string Easing = "linear";
    public const float EdgeFriction = 0.15f;
    public const bool Infinite = true;
    public const int InitialSlide = 0;
    public const string LazyLoad = "ondemand";
    public const bool MobileFirst = true;
    public const bool PauseOnFocus = true;
    public const bool PauseOnHover = true;
    public const bool PauseOnDotsHover = false;
    public const string RespondTo = "window";
    public const int Rows = 1;
    public const string Slide = "";
    public const int SlidesPerRow = 1;
    public const int SlidesToShow = 1;
    public const int SlidesToScroll = 1;
    public const int Speed = 300;
    public const bool Swipe = true;
    public const bool SwipeToSlide = true;
    public const bool TouchMove = true;
    public const int TouchThreshold = 5;
    public const bool UseCss = true;
    public const bool UseTransform = true;
    public const bool VariableWidth = false;
    public const bool Vertical = false;
    public const bool VerticalSwiping = false;
    public const bool RightToLeft = false;
    public const bool WaitForAnimate = true;
    public const int ZIndex = 1000;
}
