<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <!-- This is disabled, because restoring Slick via LibMan is flaky, see 
    https://github.com/Lombiq/GitHub-Actions/issues/549. So, we keep the library in the repository. Uncomment this
    temporarily while updating the Slick snapshot locally. It's not enabled locally either because we don't gain
    anything by it except for the rare cases of updates, but since LibMan touches the files, they'll show up as changed
    in Git (at least in Git Extensions), even though their contents didn't change. -->
    <UseLibMan>false</UseLibMan>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.23.osoe-925" />

  <PropertyGroup>
    <Title>Lombiq UI Kit for Orchard Core</Title>
    <CopyrightYear>2021</CopyrightYear>
    <DescriptionBody>This module contains reusable shapes like text editors, custom-style checkboxes, dropdown editors, and in the future potentially more complex editors.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;UI;UIKit;front-end</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-UIKit</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\..\test\Lombiq.UITestingToolbox\Lombiq.Tests.UI.AppExtensions\Lombiq.Tests.UI.AppExtensions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.Tests.UI.AppExtensions" Version="14.2.2-alpha.21.osoe-925" />
  </ItemGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.23.osoe-925" />
</Project>
